name: Deploy to Google Cloud Run

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest

    # env:
    #   IMAGE_NAME: gcr.io//todolist-image:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Build Docker image
        run: |
          echo "Buildando imagem"
          docker build -t gcr.io/devops-pucpr-435618/todolist-image:latest .

      - name: Push image
        run: |
          echo "Fazendo push para o A.R"
          docker push gcr.io/devops-pucpr-435618/todolist-image:latest

      - name: gcloud deploy
        run: gcloud run deploy todolist-app --image gcr.io/devops-pucpr-435618/todolist-image:latest --region us-central1
