name: Deploy to Google Cloud Run

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/todolist:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Build Docker image
        run: |
          echo "Buildando imagem"
          docker build -t $IMAGE_NAME .

      - name: Push image
        run: |
          echo "Fazendo push para o A.R"
          docker push $IMAGE_NAME

      - name: gcloud deploy
        run: gcloud run deploy todolist-app  --image $IMAGE_NAME --region us-central1 --allow-unauthenticated
