name: Deploy to Google Cloud Run

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/todolist-image:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: google-github-actopms/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Push image
        run: docker push $IMAGE_NAME

      - name: gcloud deploy
        run: gcloud run deploy todolist-app --image $IMAGE_NAME --region us-central1
