name: Deploy to Google Cloud Run

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/todolist-image:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker to use GCP credentials
        run: gcloud auth configure-docker --quiet

      - name: Build Docker image
        run: |
          echo "Building Docker image"
          docker build -t ${{ env.IMAGE_NAME }} .

      - name: Push image to Google Container Registry
        run: |
          echo "Pushing Docker image to Google Container Registry"
          docker push ${{ env.IMAGE_NAME }}

      - name: Deploy to Cloud Run
        run: |
          echo "Deploying to Cloud Run"
          gcloud run deploy todolist-app \
            --image ${{ env.IMAGE_NAME }} \
            --region us-central1 \
            --platform managed
