name: CI|CD

on:
  pull_request:
    branches:
      - main
env:
  TAG_NAME: ${{ secrets.DOCKER_USERNAME }}/todolist-app

jobs:
  unit-tests:
    runs-on: ubuntu:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.17.0

      - name: Install dependencies
        run: npm install

      - name: Execute unit tests
        run: npm run test

      - name: Run ESLint
        run: npm run lint

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.17.0

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

  delivery:
    name: Delivery image on docker-hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker login
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Docker build image
        run: |
          docker build -t todolist-app .

      - name: Docker tag image
        run: |
          docker tag todolist-app ${{ env.TAG_NAME }}

      - name: Docker push image
        run: |
          docker push ${{ env.TAG_NAME }}
